name: Unit Test

on: [ push, pull_request ]

jobs:
  lambda-deployment-changes:
    name: Terraform changes
    runs-on: self-hosted
    
    env:
      working-directory: './nueees-tools'

    steps:
    - name: Checkout main repo
    - uses: actions/checkout@v2
    
    - uses: hashicorp/setup-terraform@v1.2.1

    - name: 'Terraform Init'
      run: terraform init
      working-directory: ${{ env.working-directory }}
